# Generated by Django 3.2.4 on 2023-05-24 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.CharField(editable=False, max_length=9, primary_key=True, serialize=False, unique=True)),
                ('Image', models.ImageField(default='default.jpg', upload_to='profile_pics/')),
                ('Name', models.CharField(max_length=200, null=True)),
                ('Phone', models.CharField(max_length=200, null=True)),
                ('Email', models.CharField(max_length=200, null=True)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('Twitter', models.URLField(null=True)),
                ('Instagram', models.URLField(null=True)),
                ('Facebook', models.URLField(null=True)),
                ('point', models.FloatField(default=0, max_length=200)),
                ('Address', models.CharField(max_length=200, null=True)),
                ('DataCreated', models.DateTimeField(auto_now_add=True, null=True)),
                ('auth_token', models.IntegerField(editable=False, null=True)),
                ('User', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('Create', models.DateTimeField(auto_now_add=True, null=True)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('Image', models.ImageField(default='default.jpg', upload_to='voucher_pics/')),
                ('CreateAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('Name', models.CharField(max_length=200, null=True)),
                ('Phone', models.CharField(max_length=200, null=True)),
                ('Email', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrashDetail',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('recycle', models.IntegerField(null=True)),
                ('dangerous', models.IntegerField(null=True)),
                ('othergarbage', models.IntegerField(null=True)),
                ('description', models.CharField(max_length=300, null=True)),
                ('iduser', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.customer')),
            ],
        ),
        migrations.CreateModel(
            name='TrashType',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('Name', models.CharField(max_length=10, null=True)),
                ('Point', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('AmountAvailable', models.IntegerField(null=True)),
                ('Create', models.DateTimeField(auto_now_add=True, null=True)),
                ('body', models.TextField()),
                ('NeededPoint', models.FloatField(default='0', max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.partner')),
            ],
        ),
        migrations.CreateModel(
            name='TrashList',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('createat', models.DateTimeField(auto_now_add=True, null=True)),
                ('numoftrash', models.IntegerField(null=True, verbose_name='NumTrash')),
                ('totalscore', models.FloatField(max_length=200, null=True, verbose_name='Total Score')),
                ('description', models.TextField(blank=True)),
                ('iduser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.customer')),
                ('trash_detail', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.trashdetail')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerVouchers',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('Buy_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('GenerateCode', models.CharField(editable=False, max_length=9, null=True, unique=True)),
                ('Customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.customer')),
                ('Voucher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.voucher')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('body', models.TextField()),
                ('data_added', models.DateTimeField(auto_now_add=True)),
                ('name', models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.customer')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='website.voucher')),
            ],
        ),
    ]
